Created A #0
Created A #1
Created A #2
Created A #3
Created A #4
In B constructor!
B destructor!
Destroyed A #4
Destroyed A #3
Destroyed A #2
Destroyed A #1
Destroyed A #0
Created A #5
Created A #6
Created A #7
'throws' threw an exception: rethrowing!
Destroyed A #7
Destroyed A #6
Destroyed A #5
In B catch block with int 7: auto rethrowing
Caught exception!
exit 0
